export interface BookRecord {
  id: string;
  callNumber: string;
  title: string;
  author: string;
  publisher: string;
  year: number;
  edition?: string;
  isbn: string;
  ddcCode: string;
  ddcCategory: string;
  shelfLocation: string;
  shelfColorBadge: 'emerald' | 'blue' | 'amber' | 'purple' | 'rose';
  totalCopies: number;
  availableCopies: number;
  isAvailable: boolean;
  synopsis: string;
  pages: number;
  language: string;
}

export const DDC_CATEGORIES = [
  { code: 'ALL', name: 'Semua Klasifikasi' },
  { code: '657', name: '657 — Akuntansi & Auditing' },
  { code: '658', name: '658 — Manajemen & Bisnis' },
  { code: '330', name: '330 — Teori Ekonomi & Ekonometrika' },
  { code: '332', name: '332 — Keuangan & Pasar Modal' },
  { code: '001', name: '001 — Metodologi Penelitian' },
];

export const KATALOG_BUKU_DATA: BookRecord[] = [
  {
    id: 'bk-001',
    callNumber: '657.042 WEY f',
    title: 'Financial Accounting: IFRS Edition (4th Edition)',
    author: 'Jerry J. Weygandt, Paul D. Kimmel, Donald E. Kieso',
    publisher: 'John Wiley & Sons, Inc.',
    year: 2020,
    edition: '4th Edition',
    isbn: '978-1-119-50430-6',
    ddcCode: '657',
    ddcCategory: 'Akuntansi & Auditing',
    shelfLocation: 'Rak A-01 (Lantai 1)',
    shelfColorBadge: 'emerald',
    totalCopies: 4,
    availableCopies: 3,
    isAvailable: true,
    synopsis:
      'Buku teks standar rujukan internasional akuntansi keuangan berorientasi standar IFRS. Mengupas tuntas siklus pencatatan akuntansi, pengakuan pendapatan, valuasi aset lancar dan tetap, kewajiban, ekuitas pemegang saham, serta analisis laporan arus kas komprehensif.',
    pages: 896,
    language: 'Inggris',
  },
  {
    id: 'bk-002',
    callNumber: '657.044 KIE i',
    title: 'Intermediate Accounting: IFRS Edition (3rd Edition)',
    author: 'Donald E. Kieso, Jerry J. Weygandt, Terry D. Warfield',
    publisher: 'John Wiley & Sons',
    year: 2018,
    edition: '3rd Edition',
    isbn: '978-1-119-37293-6',
    ddcCode: '657',
    ddcCategory: 'Akuntansi & Auditing',
    shelfLocation: 'Rak A-02 (Lantai 1)',
    shelfColorBadge: 'emerald',
    totalCopies: 3,
    availableCopies: 1,
    isAvailable: true,
    synopsis:
      'Literatur fundamental akuntansi keuangan tingkat menengah. Fokus pada kerangka konseptual pelaporan keuangan, instrumen derivatif, sewa guna usaha (leases), imbalan kerja, pajak tangguhan, dan pelaporan segmen.',
    pages: 1424,
    language: 'Inggris',
  },
  {
    id: 'bk-003',
    callNumber: '657.42 HAN c',
    title: 'Cost Management: Accounting & Control (6th Edition)',
    author: 'Don R. Hansen, Maryanne M. Mowen, Liming Guan',
    publisher: 'South-Western Cengage Learning',
    year: 2021,
    edition: '6th Edition',
    isbn: '978-0-324-65922-1',
    ddcCode: '657',
    ddcCategory: 'Akuntansi & Auditing',
    shelfLocation: 'Rak A-03 (Lantai 1)',
    shelfColorBadge: 'emerald',
    totalCopies: 5,
    availableCopies: 0,
    isAvailable: false,
    synopsis:
      'Panduan manajemen biaya stratejik, penetapan harga pokok berbasis aktivitas (Activity-Based Costing/ABC), Lean Accounting, Target Costing, serta evaluasi kinerja divisi dengan Balanced Scorecard.',
    pages: 848,
    language: 'Inggris',
  },
  {
    id: 'bk-004',
    callNumber: '657.45 ARE a',
    title: 'Auditing and Assurance Services: An Integrated Approach (17th Edition)',
    author: 'Alvin A. Arens, Randal J. Elder, Mark S. Beasley, Chris E. Hogan',
    publisher: 'Pearson Education',
    year: 2020,
    edition: '17th Edition',
    isbn: '978-0-135-17614-7',
    ddcCode: '657',
    ddcCategory: 'Akuntansi & Auditing',
    shelfLocation: 'Rak A-04 (Lantai 1)',
    shelfColorBadge: 'emerald',
    totalCopies: 4,
    availableCopies: 2,
    isAvailable: true,
    synopsis:
      'Rujukan otoritatif profesi akuntan publik. Membahas audit berbasis risiko (ISA), bukti audit, prosedur analitis, sampling audit statistik, pengendalian internal COSO, dan etika profesional auditor independen.',
    pages: 880,
    language: 'Inggris',
  },
  {
    id: 'bk-005',
    callNumber: '657.835 IKR a',
    title: 'Akuntansi Sektor Publik: Teori, Konsep, dan Aplikasi di Indonesia',
    author: 'Prof. Dr. Mohamad Khusaini, S.E., M.Si., M.A.',
    publisher: 'UB Press',
    year: 2022,
    edition: 'Cetakan Ke-2',
    isbn: '978-602-432-841-3',
    ddcCode: '657',
    ddcCategory: 'Akuntansi & Auditing',
    shelfLocation: 'Rak A-05 (Lantai 1)',
    shelfColorBadge: 'emerald',
    totalCopies: 6,
    availableCopies: 4,
    isAvailable: true,
    synopsis:
      'Analisis komprehensif akuntansi pemerintahan dan organisasi nirlaba di Indonesia. Mengulas Standar Akuntansi Pemerintahan (SAP berbasis akrual), penganggaran publik berbasis kinerja, dan pelaporan keuangan BLU/BLUD.',
    pages: 360,
    language: 'Indonesia',
  },
  {
    id: 'bk-006',
    callNumber: '658.8 KOT m',
    title: 'Marketing Management (16th Global Edition)',
    author: 'Philip Kotler, Kevin Lane Keller, Alexander Chernev',
    publisher: 'Pearson Global',
    year: 2022,
    edition: '16th Edition',
    isbn: '978-1-292-40481-3',
    ddcCode: '658',
    ddcCategory: 'Manajemen & Bisnis',
    shelfLocation: 'Rak B-01 (Lantai 1)',
    shelfColorBadge: 'blue',
    totalCopies: 5,
    availableCopies: 3,
    isAvailable: true,
    synopsis:
      'Karya legendaris pemasaran modern abad ke-21. Menguraikan perumusan proposisi nilai, analisis perilaku konsumen digital, segmentasi dan targeting omnichannel, manajemen ekuitas merek, serta integrasi AI dalam pemasaran.',
    pages: 832,
    language: 'Inggris',
  },
  {
    id: 'bk-007',
    callNumber: '658.3 ROB o',
    title: 'Organizational Behavior (18th Global Edition)',
    author: 'Stephen P. Robbins, Timothy A. Judge',
    publisher: 'Pearson Education',
    year: 2019,
    edition: '18th Edition',
    isbn: '978-1-292-25923-9',
    ddcCode: '658',
    ddcCategory: 'Manajemen & Bisnis',
    shelfLocation: 'Rak B-02 (Lantai 1)',
    shelfColorBadge: 'blue',
    totalCopies: 4,
    availableCopies: 2,
    isAvailable: true,
    synopsis:
      'Kajian perilaku organisasi komprehensif pada level individu, kelompok, dan sistem organisasional. Menelaah dinamika kepemimpinan transformasional, motivasi kerja, negosiasi konflik, dan perubahan budaya korporasi.',
    pages: 752,
    language: 'Inggris',
  },
  {
    id: 'bk-008',
    callNumber: '658.5 HEI o',
    title: 'Operations Management: Sustainability and Supply Chain Management (13th Edition)',
    author: 'Jay Heizer, Barry Render, Chuck Munson',
    publisher: 'Pearson',
    year: 2020,
    edition: '13th Edition',
    isbn: '978-0-135-22874-6',
    ddcCode: '658',
    ddcCategory: 'Manajemen & Bisnis',
    shelfLocation: 'Rak B-03 (Lantai 1)',
    shelfColorBadge: 'blue',
    totalCopies: 3,
    availableCopies: 2,
    isAvailable: true,
    synopsis:
      'Prinsip operasional manufaktur dan jasa modern. Mencakup desain produk, manajemen rantai pasok global (SCM), kendali mutu Six Sigma, peramalan permintaan, perencanaan kapasitas, dan lean operations.',
    pages: 896,
    language: 'Inggris',
  },
  {
    id: 'bk-009',
    callNumber: '658.401 DAV s',
    title: 'Strategic Management: Concepts and Cases (17th Global Edition)',
    author: 'Fred R. David, Forest R. David',
    publisher: 'Pearson Education',
    year: 2021,
    edition: '17th Edition',
    isbn: '978-1-292-31589-8',
    ddcCode: '658',
    ddcCategory: 'Manajemen & Bisnis',
    shelfLocation: 'Rak B-04 (Lantai 1)',
    shelfColorBadge: 'blue',
    totalCopies: 4,
    availableCopies: 0,
    isAvailable: false,
    synopsis:
      'Metodologi perencanaan strategis bisnis tiga tahap: perumusan (Matriks SWOT, BCG, SPACE, QSPM), implementasi lintas fungsi manajemen, serta evaluasi dan kendali tata kelola korporat.',
    pages: 672,
    language: 'Inggris',
  },
  {
    id: 'bk-010',
    callNumber: '658.15 BRI f',
    title: 'Financial Management: Theory & Practice (16th Edition)',
    author: 'Eugene F. Brigham, Michael C. Ehrhardt',
    publisher: 'Cengage Learning',
    year: 2020,
    edition: '16th Edition',
    isbn: '978-1-337-90260-1',
    ddcCode: '658',
    ddcCategory: 'Manajemen & Bisnis',
    shelfLocation: 'Rak B-05 (Lantai 1)',
    shelfColorBadge: 'blue',
    totalCopies: 4,
    availableCopies: 3,
    isAvailable: true,
    synopsis:
      'Manajemen keuangan korporat tingkat lanjut: penganggaran modal (capital budgeting), struktur modal optimal, biaya modal (WACC), kebijakan dividen, merger dan akuisisi, serta manajemen modal kerja.',
    pages: 1200,
    language: 'Inggris',
  },
  {
    id: 'bk-011',
    callNumber: '330 MAN p',
    title: 'Principles of Economics (9th Edition)',
    author: 'N. Gregory Mankiw',
    publisher: 'Cengage Learning',
    year: 2021,
    edition: '9th Edition',
    isbn: '978-0-357-03831-4',
    ddcCode: '330',
    ddcCategory: 'Teori Ekonomi & Ekonometrika',
    shelfLocation: 'Rak C-01 (Lantai 1)',
    shelfColorBadge: 'amber',
    totalCopies: 6,
    availableCopies: 5,
    isAvailable: true,
    synopsis:
      'Buku teks pengantar ekonomi paling populer di dunia. Menjelaskan 10 Prinsip Ekonomi, mekanisme pasar penawaran dan permintaan, elastisitas, eksternalitas, pasar persaingan sempurna dan monopoli, serta makroekonomi agregat.',
    pages: 864,
    language: 'Inggris',
  },
  {
    id: 'bk-012',
    callNumber: '330.015 GUJ b',
    title: 'Basic Econometrics (5th Edition)',
    author: 'Damodar N. Gujarati, Dawn C. Porter',
    publisher: 'McGraw-Hill Education',
    year: 2019,
    edition: '5th Edition',
    isbn: '978-0-073-37577-9',
    ddcCode: '330',
    ddcCategory: 'Teori Ekonomi & Ekonometrika',
    shelfLocation: 'Rak C-02 (Lantai 1)',
    shelfColorBadge: 'amber',
    totalCopies: 5,
    availableCopies: 2,
    isAvailable: true,
    synopsis:
      'Fondasi empiris riset ekonomi kuantitatif. Mengupas analisis regresi linear berganda (OLS), uji asumsi klasik (multikolinearitas, heteroskedastisitas, autokorelasi), model data panel, dan model time-series terapan.',
    pages: 944,
    language: 'Inggris',
  },
  {
    id: 'bk-013',
    callNumber: '337 KRU i',
    title: 'International Economics: Theory and Policy (12th Global Edition)',
    author: 'Paul R. Krugman, Maurice Obstfeld, Marc J. Melitz',
    publisher: 'Pearson Education',
    year: 2022,
    edition: '12th Edition',
    isbn: '978-1-292-41687-8',
    ddcCode: '330',
    ddcCategory: 'Teori Ekonomi & Ekonometrika',
    shelfLocation: 'Rak C-03 (Lantai 1)',
    shelfColorBadge: 'amber',
    totalCopies: 3,
    availableCopies: 1,
    isAvailable: true,
    synopsis:
      'Teori perdagangan internasional dan moneter internasional oleh peraih Nobel Ekonomi. Membahas model Ricardian, Heckscher-Ohlin, instrumen kebijakan tarif, neraca pembayaran, dan rezim nilai tukar global.',
    pages: 800,
    language: 'Inggris',
  },
  {
    id: 'bk-014',
    callNumber: '332.1 MIS e',
    title: 'The Economics of Money, Banking, and Financial Markets (13th Global Edition)',
    author: 'Frederic S. Mishkin',
    publisher: 'Pearson',
    year: 2021,
    edition: '13th Edition',
    isbn: '978-1-292-40948-1',
    ddcCode: '332',
    ddcCategory: 'Keuangan & Pasar Modal',
    shelfLocation: 'Rak D-01 (Lantai 1)',
    shelfColorBadge: 'purple',
    totalCopies: 4,
    availableCopies: 3,
    isAvailable: true,
    synopsis:
      'Kajian mendalam sistem moneter dan perbankan sentral. Menguraikan suku bunga, struktur perbankan komersial, transmisi kebijakan moneter, krisis keuangan sistemik, dan regulasi stabilitas makroprudensial.',
    pages: 720,
    language: 'Inggris',
  },
  {
    id: 'bk-015',
    callNumber: '332.632 BOD i',
    title: 'Investments (12th Edition)',
    author: 'Zvi Bodie, Alex Kane, Alan J. Marcus',
    publisher: 'McGraw-Hill Education',
    year: 2021,
    edition: '12th Edition',
    isbn: '978-1-260-01383-2',
    ddcCode: '332',
    ddcCategory: 'Keuangan & Pasar Modal',
    shelfLocation: 'Rak D-02 (Lantai 1)',
    shelfColorBadge: 'purple',
    totalCopies: 4,
    availableCopies: 2,
    isAvailable: true,
    synopsis:
      'Kitab rujukan analis sekuritas dan manajer investasi portofolio. Membahas teori portofolio Markowitz, Capital Asset Pricing Model (CAPM), Arbitrage Pricing Theory (APT), valuasi obligasi, dan efisiensi pasar modal.',
    pages: 1040,
    language: 'Inggris',
  },
  {
    id: 'bk-016',
    callNumber: '332.645 HUL o',
    title: 'Options, Futures, and Other Derivatives (11th Global Edition)',
    author: 'John C. Hull',
    publisher: 'Pearson Education',
    year: 2022,
    edition: '11th Edition',
    isbn: '978-1-292-41065-4',
    ddcCode: '332',
    ddcCategory: 'Keuangan & Pasar Modal',
    shelfLocation: 'Rak D-03 (Lantai 1)',
    shelfColorBadge: 'purple',
    totalCopies: 3,
    availableCopies: 0,
    isAvailable: false,
    synopsis:
      'Panduan terlengkap produk derivatif keuangan dan rekayasa finansial. Mencakup kontrak berjangka, opsi Eropa/Amerika, model Black-Scholes-Merton, lindung nilai (hedging), swaps, dan pengukuran Value at Risk (VaR).',
    pages: 912,
    language: 'Inggris',
  },
  {
    id: 'bk-017',
    callNumber: '001.42 SUG m',
    title: 'Metode Penelitian Kuantitatif, Kualitatif, dan R&D',
    author: 'Prof. Dr. Sugiyono',
    publisher: 'Alfabeta Bandung',
    year: 2021,
    edition: 'Cetakan Ke-31',
    isbn: '978-979-843-364-0',
    ddcCode: '001',
    ddcCategory: 'Metodologi Penelitian',
    shelfLocation: 'Rak E-01 (Lantai 1)',
    shelfColorBadge: 'rose',
    totalCopies: 8,
    availableCopies: 6,
    isAvailable: true,
    synopsis:
      'Buku pedoman penyusunan skripsi, tesis, dan disertasi terfavorit mahasiswa ekonomi. Menyajikan tahapan perumusan masalah, hipotesis, teknik sampling, validitas reliabilitas kuesioner, hingga analisis data statistik.',
    pages: 464,
    language: 'Indonesia',
  },
  {
    id: 'bk-018',
    callNumber: '001.42 SEK r',
    title: 'Research Methods for Business: A Skill-Building Approach (8th Edition)',
    author: 'Uma Sekaran, Roger Bougie',
    publisher: 'John Wiley & Sons Ltd',
    year: 2020,
    edition: '8th Edition',
    isbn: '978-1-119-56294-8',
    ddcCode: '001',
    ddcCategory: 'Metodologi Penelitian',
    shelfLocation: 'Rak E-02 (Lantai 1)',
    shelfColorBadge: 'rose',
    totalCopies: 5,
    availableCopies: 3,
    isAvailable: true,
    synopsis:
      'Pendekatan metodologi ilmiah terstruktur untuk riset manajerial dan bisnis. Membahas kerangka teoretis konseptual, desain eksperimen, teknik pengukuran skala likert, kuesioner daring, dan penulisan laporan akhir.',
    pages: 448,
    language: 'Inggris',
  },
];
